#!/bin/sh

gdmauth=$XAUTHORITY
unset XAUTHORITY
export XAUTHORITY="$XDG_CONFIG_HOME/.xauth"

# other settings
xauth merge "$gdmauth"
xrdb "$HOME/.config/Xresources"
xset r rate 270 50
xsetroot -cursor_name left_ptr
setxkbmap us altgr-intl

# programs
conky &
conky -m 1 &
dunst &
mpDris2 &
rem-notify &
slstatus &
unclutter &
sxhkd &
discord &
signal-desktop &
anki &
feh --no-fehbg --bg-fill "$HOME/pics/wallpaper.jpg" &

exec dwm-session
