#!/bin/sh

# Display configuration
if [ "$(hostname)" = "archlinux-desktop" ]; then
	xrandr --output DVI-D-0 --mode 1440x900 --pos 0x0 --rotate right \
		--output DVI-D-1 --mode 1920x1080 --pos 900x320 --rotate normal --primary
fi

gdmauth=$XAUTHORITY
unset XAUTHORITY
export XAUTHORITY="$XDG_CONFIG_HOME/.xauth"

# other settings
xauth merge "$gdmauth"
xrdb "$HOME/.config/Xresources"
xset r rate 270 50
xsetroot -cursor_name left_ptr
setxkbmap us altgr-intl

# programs
conky &
conky -m 1 &
dunst &
mpDris2 &
rem-notify &
slstatus &
unclutter &
sxhkd &
discord &
signal-desktop &
feh --no-fehbg --bg-fill "$HOME/pics/wallpaper.jpg" &

exec dwm-start
#exec openbox
