#!/bin/sh

# Default options
alias \
    ls="ls -Fh" \
	diff="diff --color=auto" \
	ip="ip -color=auto" \
	gdb="gdb -q" \
    cp="cp -iv" \
    df='df -h' \
    du='du -h' \
    rm="trash" \
    cfg='git --git-dir=$HOME/.local/share/dotfiles/ --work-tree=$HOME' \

# Shortcuts
alias \
    SS="sudo systemctl" \
    SU="systemctl --user" \
    g="git" \
    gd="git diff" \
    gl="git log" \
    gs="git status" \
    iv=sxiv \
    ka=killall \
    p="paru" \
    sl="ls" \
	se="sudo $EDITOR" \
	e="$EDITOR" \
    z="zathura"
